--liquibase formatted sql

--changeset admin:001:create-users-table context:ddl
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE users;

--changeset admin:002:create-categories-table context:ddl
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE categories;

--changeset admin:003:create-products-table context:ddl
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    category_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
--rollback DROP TABLE products;

--changeset admin:004:add-indexes context:ddl
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_users_email ON users(email);
--rollback DROP INDEX idx_products_category_id; DROP INDEX idx_products_name; DROP INDEX idx_users_email;

--changeset admin:010:seed-categories context:dml
INSERT ALL
INTO categories (name, description) VALUES ('Electronics', 'Electronic devices and gadgets')
INTO categories (name, description) VALUES ('Clothing', 'Fashion and apparel')
INTO categories (name, description) VALUES ('Books', 'Books and literature')
INTO categories (name, description) VALUES ('Home & Garden', 'Home improvement and gardening supplies')
SELECT 1 FROM DUAL;
--rollback DELETE FROM categories WHERE name IN ('Electronics', 'Clothing', 'Books', 'Home & Garden');

--changeset admin:011:seed-products context:dml
INSERT ALL
INTO products (name, description, price, category_id) VALUES ('Laptop', 'High-performance laptop computer', 999.99, 1)
INTO products (name, description, price, category_id) VALUES ('Smartphone', 'Latest model smartphone', 699.99, 1)
INTO products (name, description, price, category_id) VALUES ('T-Shirt', 'Cotton t-shirt', 19.99, 2)
INTO products (name, description, price, category_id) VALUES ('Jeans', 'Blue denim jeans', 49.99, 2)
INTO products (name, description, price, category_id) VALUES ('Programming Book', 'Learn to code', 29.99, 3)
INTO products (name, description, price, category_id) VALUES ('Garden Tools', 'Complete garden tool set', 79.99, 4)
SELECT 1 FROM DUAL;
--rollback DELETE FROM products WHERE name IN ('Laptop', 'Smartphone', 'T-Shirt', 'Jeans', 'Programming Book', 'Garden Tools');

--changeset admin:012:seed-users context:dml
INSERT ALL
INTO users (username, email) VALUES ('admin', 'admin@example.com')
INTO users (username, email) VALUES ('user1', 'user1@example.com')
INTO users (username, email) VALUES ('user2', 'user2@example.com')
SELECT 1 FROM DUAL;
--rollback DELETE FROM users WHERE username IN ('admin', 'user1', 'user2');
