--liquibase formatted sql

--changeset admin:001:create-users-table context:ddl
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE users;

--changeset admin:002:create-categories-table context:ddl
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
--rollback DROP TABLE categories;

--changeset admin:003:create-products-table context:ddl
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    category_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
--rollback DROP TABLE products;

--changeset admin:004:add-indexes context:ddl
-- Indexes will be created manually if needed
--rollback DROP INDEX idx_products_category_id; DROP INDEX idx_products_name; DROP INDEX idx_users_email;

--changeset admin:010:seed-categories context:dml
MERGE INTO categories c
USING (SELECT 'Electronics' as name, 'Electronic devices and gadgets' as description FROM DUAL
       UNION ALL SELECT 'Clothing', 'Fashion and apparel' FROM DUAL
       UNION ALL SELECT 'Books', 'Books and literature' FROM DUAL
       UNION ALL SELECT 'Home & Garden', 'Home improvement and gardening supplies' FROM DUAL) s
ON (c.name = s.name)
WHEN NOT MATCHED THEN
  INSERT (name, description) VALUES (s.name, s.description);
--rollback DELETE FROM categories WHERE name IN ('Electronics', 'Clothing', 'Books', 'Home & Garden');

--changeset admin:011:seed-products context:dml
MERGE INTO products p
USING (SELECT 'Laptop' as name, 'High-performance laptop computer' as description, 999.99 as price, 1 as category_id FROM DUAL
       UNION ALL SELECT 'Smartphone', 'Latest model smartphone', 699.99, 1 FROM DUAL
       UNION ALL SELECT 'T-Shirt', 'Cotton t-shirt', 19.99, 2 FROM DUAL
       UNION ALL SELECT 'Jeans', 'Blue denim jeans', 49.99, 2 FROM DUAL
       UNION ALL SELECT 'Programming Book', 'Learn to code', 29.99, 3 FROM DUAL
       UNION ALL SELECT 'Garden Tools', 'Complete garden tool set', 79.99, 4 FROM DUAL) s
ON (p.name = s.name)
WHEN NOT MATCHED THEN
  INSERT (name, description, price, category_id) VALUES (s.name, s.description, s.price, s.category_id);
--rollback DELETE FROM products WHERE name IN ('Laptop', 'Smartphone', 'T-Shirt', 'Jeans', 'Programming Book', 'Garden Tools');

--changeset admin:012:seed-users context:dml
MERGE INTO users u
USING (SELECT 'admin' as username, 'admin@example.com' as email FROM DUAL
       UNION ALL SELECT 'user1', 'user1@example.com' FROM DUAL
       UNION ALL SELECT 'user2', 'user2@example.com' FROM DUAL) s
ON (u.username = s.username)
WHEN NOT MATCHED THEN
  INSERT (username, email) VALUES (s.username, s.email);
--rollback DELETE FROM users WHERE username IN ('admin', 'user1', 'user2');
